---
- name: Check if newrelic.yml exists
  stat:
    path: "{{ server_root }}/newrelic/newrelic.yml"
  register: newrelic_yml
  become: true

- name: Handle existing newrelic.yml
  when: newrelic_yml.stat.exists
  block:
  - name: get stat for .new file
    stat:
      path: "{{ server_root }}/newrelic/newrelic.yml.new"
    register: newrelic_yml_new
    become: true

  - name: check if new and existing are different
    set_fact:
      newrelic_yml_changed: "{{ newrelic_yml.stat.checksum != newrelic_yml_new.stat.checksum }}"

  - name: Check if newrelic.yml.prev exists
    stat:
      path: "{{ server_root }}/newrelic/newrelic.yml.prev"
    register: newrelic_yml_prev
    become: true

  - name: Check if newrelic.yml.orig exists
    stat:
      path: "{{ server_root }}/newrelic/newrelic.yml.orig"
    register: newrelic_yml_orig
    become: true

  # If either a .prev or a .orig file exists, we've already copied the
  # original file if there was one. Just copy the current file to .prev,
  # if it's different from the new file.
  - name: Backup most recent newrelic.yml to newrelic.yml.prev
    when: (newrelic_yml_prev.stat.exists or newrelic_yml_orig.stat.exists) and newrelic_yml_changed
    copy:
      src: "{{ server_root }}/newrelic/newrelic.yml"
      dest: "{{ server_root }}/newrelic/newrelic.yml.prev"
      remote_src: true
      owner: "{{ server_user }}"
      group: "{{ server_group }}"
      mode: "0640"
    become: true
    # This task is not idempotent on the second run, only on subsequent runs,
    # so disable idempotence testing.
    tags:
      - molecule-idempotence-notest

  # If neither .prev nor .orig exists, we've never run before.
  # Copy the existing newrelic.yml to .orig no matter what.
  - name: Backup original newrelic.yml to newrelic.yml.orig
    when: not newrelic_yml_prev.stat.exists and not newrelic_yml_orig.stat.exists
    copy:
      src: "{{ server_root }}/newrelic/newrelic.yml"
      dest: "{{ server_root }}/newrelic/newrelic.yml.orig"
      remote_src: true
      owner: "{{ server_user }}"
      group: "{{ server_group }}"
      mode: "0640"
    become: true
    # This task is not idempotent on the second run, only on subsequent runs,
    # so disable idempotence testing.
    tags:
      - molecule-idempotence-notest
