---
- name: Tomcat -javaagent setup
  lineinfile:
    dest: "{{ jvm_conf_file }}"
    line: export JAVA_OPTS="$JAVA_OPTS -javaagent:{{ server_root }}/newrelic/newrelic.jar"
    create: yes
    mode: "0755"
  when: server_type == "tomcat"
  become: yes
  notify:
    - restart web server

- name: Jetty -javaagent setup
  lineinfile:
    dest: "{{ jvm_conf_file }}"
    line: JAVA_OPTIONS="$JAVA_OPTIONS -javaagent:{{ server_root }}/newrelic/newrelic.jar"
    create: no
  when: server_type == "jetty"
  become: yes
  notify:
    - restart web server

- name: Wildfly standalone -javaagent setup
  lineinfile:
    dest: "{{ jvm_conf_file }}"
    line: JAVA_OPTS="$JAVA_OPTS -javaagent:{{ server_root }}/newrelic/newrelic.jar"
    create: no
  when: server_type == "wildfly"
  become: yes
  notify:
    - restart web server
