---
#- name: Merge default and user config
#  set_fact:
#    nr_java_agent_config: "{{ nr_java_agent_default_config | combine(nr_java_agent_config, recursive=True) }}"

#- name: Merge host config
#  set_fact:
#    nr_java_agent_config: "{{ nr_java_agent_config | combine(nr_java_agent_host_config, recursive=True) }}"

#- name: Validate configuration
#  import_tasks: validate.yml

- name: Install and configure the agent
  import_tasks: install.yml

- name: Enable the agent
  import_tasks: enable.yml
