---
- name: validate Jetty jvm conf file exists
  when: server_type == "jetty"
  block:
    - name: check jvm conf file existence
      stat:
        path: "{{ jvm_conf_file }}"
      register: jvm_conf
    - name: fail if jvm conf file does not exist
      fail:
        msg: For Jetty installation the jvm conf file {{ jvm_conf_file }} should already exist
      when: not jvm_conf.stat.exists

- name: Validate local config file exists, if provided
  when: nr_java_agent_config_file is defined and not (nr_java_agent_config_file_is_remote is defined | default(false))
  block:
    - name: Check supplied local config file existence
      stat:
        path: "{{ nr_java_agent_config_file }}"
      register: agent_conf
      delegate_to: localhost
    - name: Fail if supplied local config file does not exist
      fail:
        msg: Config file specified at {{ nr_java_agent_config_file }} does not exist on the local host
      when: not agent_conf.stat.exists

- name: Validate remote config file exists, if provided
  when: nr_java_agent_config_file is defined and (nr_java_agent_config_file_is_remote is defined and nr_java_agent_config_file_is_remote | default(false))
  block:
    - name: Check supplied remote config file existence
      stat:
        path: "{{ nr_java_agent_config_file }}"
      register: agent_conf
    - name: Fail if supplied remote config file does not exist
      fail:
        msg: Config file specified at {{ nr_java_agent_config_file }} does not exist on the remote host
      when: not agent_conf.stat.exists
